name: Build and Deploy Terraform code
# Controls when the action will run. 
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push for the main branch
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Directory
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: aws-terraform-hybrid-dns/global/iam
            tf_ver: 1.2.3
            auto_apply: no
          - directory: aws-terraform-hybrid-dns/us-east-1
            tf_ver: 1.2.3
            auto_apply: no
          - directory: aws-terraform-hybrid-dns/us-east-2
            tf_ver: 1.2.3
            auto_apply: no
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.tf_ver }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out=build.plan
        continue-on-error: true
